/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BotConfig {
  'principal' : Principal,
  'balance' : number,
  'isPremium' : boolean,
  'difficulty' : BotDifficulty,
}
export type BotDifficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export type GameMode = { 'timed' : null } |
  { 'challenge' : null } |
  { 'advanced' : null } |
  { 'experimental' : null } |
  { 'custom' : null } |
  { 'demo' : null } |
  { 'team' : null } |
  { 'superLudo' : null } |
  { 'quick' : null } |
  { 'tournament' : null } |
  { 'classic' : null } |
  { 'twoVsTwo' : null } |
  { 'practice' : null } |
  { 'bonus' : null } |
  { 'master' : null } |
  { 'copyClassic' : null } |
  { 'copyFast' : null };
export interface GameSession {
  'id' : Principal,
  'status' : GameStatus,
  'betAmount' : number,
  'mode' : GameMode,
  'createdAt' : bigint,
  'winner' : [] | [Principal],
  'isDemo' : boolean,
  'players' : Array<Principal>,
  'rankedStatus' : RankedStatus,
}
export type GameStatus = { 'active' : null } |
  { 'completed' : null } |
  { 'waiting' : null };
export interface OfficialWallet { 'balance' : number, 'address' : string }
export interface Player {
  'principal' : Principal,
  'gamesPlayed' : number,
  'isPremium' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'color' : string,
  'wins' : number,
  'losses' : number,
  'icpBalance' : number,
  'currentGame' : [] | [Principal],
  'draws' : number,
  'lastActive' : bigint,
}
export type RankedStatus = { 'ranked' : null } |
  { 'unranked' : null };
export interface UserProfile {
  'gamesPlayed' : number,
  'isPremium' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'color' : string,
  'wins' : number,
  'losses' : number,
  'icpBalance' : number,
  'currentGame' : [] | [Principal],
  'draws' : number,
  'lastActive' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Wallet {
  'id' : Principal,
  'balance' : number,
  'createdAt' : bigint,
  'lastActive' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'activatePremiumBot' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'automaticUserInitialization' : ActorMethod<
    [],
    {
      'loginSuccess' : boolean,
      'message' : string,
      'wallet' : Wallet,
      'playerExists' : boolean,
    }
  >,
  'createGame' : ActorMethod<
    [GameMode, RankedStatus, number, boolean],
    Principal
  >,
  'createUser' : ActorMethod<[string, string], undefined>,
  'deposit' : ActorMethod<[number], boolean>,
  'getAllBots' : ActorMethod<[], Array<BotConfig>>,
  'getAllGames' : ActorMethod<[], Array<GameSession>>,
  'getAllPlayers' : ActorMethod<[], Array<Player>>,
  'getAllWallets' : ActorMethod<[], Array<Wallet>>,
  'getAvailableBots' : ActorMethod<[], Array<BotConfig>>,
  'getAvailableGames' : ActorMethod<[], Array<GameSession>>,
  'getBalance' : ActorMethod<[], number>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGame' : ActorMethod<[Principal], [] | [GameSession]>,
  'getOfficialAccount' : ActorMethod<[boolean], string>,
  'getOfficialWallets' : ActorMethod<[], Array<OfficialWallet>>,
  'getPlayer' : ActorMethod<[Principal], [] | [Player]>,
  'getSystemStats' : ActorMethod<
    [],
    {
      'totalPlayers' : bigint,
      'totalWallets' : bigint,
      'totalGames' : bigint,
      'totalBalance' : number,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWallet' : ActorMethod<[], [] | [Wallet]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFirstTime' : ActorMethod<[], boolean>,
  'isPremium' : ActorMethod<[], boolean>,
  'joinGame' : ActorMethod<[Principal, boolean], boolean>,
  'registerBot' : ActorMethod<[BotDifficulty], Principal>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePlayer' : ActorMethod<[string, string], undefined>,
  'upgradeToPremium' : ActorMethod<[], boolean>,
  'withdraw' : ActorMethod<[number], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];