/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Wallet = IDL.Record({
  'id' : IDL.Principal,
  'balance' : IDL.Float64,
  'createdAt' : IDL.Int,
  'lastActive' : IDL.Int,
});
export const GameMode = IDL.Variant({
  'timed' : IDL.Null,
  'challenge' : IDL.Null,
  'advanced' : IDL.Null,
  'experimental' : IDL.Null,
  'custom' : IDL.Null,
  'demo' : IDL.Null,
  'team' : IDL.Null,
  'superLudo' : IDL.Null,
  'quick' : IDL.Null,
  'tournament' : IDL.Null,
  'classic' : IDL.Null,
  'twoVsTwo' : IDL.Null,
  'practice' : IDL.Null,
  'bonus' : IDL.Null,
  'master' : IDL.Null,
  'copyClassic' : IDL.Null,
  'copyFast' : IDL.Null,
});
export const RankedStatus = IDL.Variant({
  'ranked' : IDL.Null,
  'unranked' : IDL.Null,
});
export const RoomType = IDL.Variant({
  'privateRoom' : IDL.Null,
  'isPublic' : IDL.Null,
});
export const BotDifficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const BotConfig = IDL.Record({
  'principal' : IDL.Principal,
  'balance' : IDL.Float64,
  'isPremium' : IDL.Bool,
  'difficulty' : BotDifficulty,
});
export const GameStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
  'waiting' : IDL.Null,
});
export const DiceRoll = IDL.Record({
  'seed' : IDL.Text,
  'diceResult' : IDL.Nat,
  'rollNumber' : IDL.Nat,
  'timestamp' : IDL.Int,
  'playerPrincipal' : IDL.Principal,
});
export const GameSession = IDL.Record({
  'id' : IDL.Principal,
  'status' : GameStatus,
  'betAmount' : IDL.Float64,
  'mode' : GameMode,
  'createdAt' : IDL.Int,
  'winner' : IDL.Opt(IDL.Principal),
  'isDemo' : IDL.Bool,
  'players' : IDL.Vec(IDL.Principal),
  'diceHistory' : IDL.Vec(DiceRoll),
  'rankedStatus' : RankedStatus,
});
export const Player = IDL.Record({
  'principal' : IDL.Principal,
  'gamesPlayed' : IDL.Float64,
  'isPremium' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'color' : IDL.Text,
  'wins' : IDL.Float64,
  'losses' : IDL.Float64,
  'icpBalance' : IDL.Float64,
  'currentGame' : IDL.Opt(IDL.Principal),
  'draws' : IDL.Float64,
  'lastActive' : IDL.Int,
});
export const MatchmakingRoom = IDL.Record({
  'id' : IDL.Principal,
  'status' : IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
    'waiting' : IDL.Null,
  }),
  'creator' : IDL.Principal,
  'playerCount' : IDL.Nat,
  'isDemo' : IDL.Bool,
  'players' : IDL.Vec(IDL.Principal),
  'gameMode' : GameMode,
  'roomType' : RoomType,
  'maxPlayers' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'gamesPlayed' : IDL.Float64,
  'isPremium' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'color' : IDL.Text,
  'wins' : IDL.Float64,
  'losses' : IDL.Float64,
  'icpBalance' : IDL.Float64,
  'currentGame' : IDL.Opt(IDL.Principal),
  'draws' : IDL.Float64,
  'lastActive' : IDL.Int,
});
export const OfficialWallet = IDL.Record({
  'balance' : IDL.Float64,
  'address' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'activatePremiumBot' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'automaticUserInitialization' : IDL.Func(
      [],
      [
        IDL.Record({
          'loginSuccess' : IDL.Bool,
          'message' : IDL.Text,
          'wallet' : Wallet,
          'playerExists' : IDL.Bool,
        }),
      ],
      [],
    ),
  'createGame' : IDL.Func(
      [GameMode, RankedStatus, IDL.Float64, IDL.Bool],
      [IDL.Principal],
      [],
    ),
  'createMatchmakingRoom' : IDL.Func(
      [RoomType, GameMode, IDL.Nat, IDL.Bool],
      [IDL.Principal],
      [],
    ),
  'createUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deposit' : IDL.Func([IDL.Float64], [IDL.Bool], []),
  'getAllBots' : IDL.Func([], [IDL.Vec(BotConfig)], ['query']),
  'getAllGames' : IDL.Func([], [IDL.Vec(GameSession)], ['query']),
  'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getAllWallets' : IDL.Func([], [IDL.Vec(Wallet)], ['query']),
  'getAvailableBots' : IDL.Func([], [IDL.Vec(BotConfig)], ['query']),
  'getAvailableGames' : IDL.Func([], [IDL.Vec(GameSession)], ['query']),
  'getAvailableRooms' : IDL.Func([], [IDL.Vec(MatchmakingRoom)], ['query']),
  'getBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDiceHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Vec(DiceRoll))],
      ['query'],
    ),
  'getGame' : IDL.Func([IDL.Principal], [IDL.Opt(GameSession)], ['query']),
  'getOfficialAccount' : IDL.Func([IDL.Bool], [IDL.Text], ['query']),
  'getOfficialWallets' : IDL.Func([], [IDL.Vec(OfficialWallet)], ['query']),
  'getPlayer' : IDL.Func([IDL.Principal], [IDL.Opt(Player)], ['query']),
  'getSystemStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalPlayers' : IDL.Int,
          'totalWallets' : IDL.Int,
          'totalGames' : IDL.Int,
          'totalBalance' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWallet' : IDL.Func([], [IDL.Opt(Wallet)], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFirstTime' : IDL.Func([], [IDL.Bool], ['query']),
  'isPremium' : IDL.Func([], [IDL.Bool], ['query']),
  'joinGame' : IDL.Func([IDL.Principal, IDL.Bool], [IDL.Bool], []),
  'joinRoom' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'leaveRoom' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'registerBot' : IDL.Func([BotDifficulty], [IDL.Principal], []),
  'rollDice' : IDL.Func(
      [IDL.Principal, IDL.Principal],
      [
        IDL.Record({
          'result' : IDL.Nat,
          'valid' : IDL.Bool,
          'seed' : IDL.Text,
        }),
      ],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePlayer' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'upgradeToPremium' : IDL.Func([], [IDL.Bool], []),
  'withdraw' : IDL.Func([IDL.Float64], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Wallet = IDL.Record({
    'id' : IDL.Principal,
    'balance' : IDL.Float64,
    'createdAt' : IDL.Int,
    'lastActive' : IDL.Int,
  });
  const GameMode = IDL.Variant({
    'timed' : IDL.Null,
    'challenge' : IDL.Null,
    'advanced' : IDL.Null,
    'experimental' : IDL.Null,
    'custom' : IDL.Null,
    'demo' : IDL.Null,
    'team' : IDL.Null,
    'superLudo' : IDL.Null,
    'quick' : IDL.Null,
    'tournament' : IDL.Null,
    'classic' : IDL.Null,
    'twoVsTwo' : IDL.Null,
    'practice' : IDL.Null,
    'bonus' : IDL.Null,
    'master' : IDL.Null,
    'copyClassic' : IDL.Null,
    'copyFast' : IDL.Null,
  });
  const RankedStatus = IDL.Variant({
    'ranked' : IDL.Null,
    'unranked' : IDL.Null,
  });
  const RoomType = IDL.Variant({
    'privateRoom' : IDL.Null,
    'isPublic' : IDL.Null,
  });
  const BotDifficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const BotConfig = IDL.Record({
    'principal' : IDL.Principal,
    'balance' : IDL.Float64,
    'isPremium' : IDL.Bool,
    'difficulty' : BotDifficulty,
  });
  const GameStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
    'waiting' : IDL.Null,
  });
  const DiceRoll = IDL.Record({
    'seed' : IDL.Text,
    'diceResult' : IDL.Nat,
    'rollNumber' : IDL.Nat,
    'timestamp' : IDL.Int,
    'playerPrincipal' : IDL.Principal,
  });
  const GameSession = IDL.Record({
    'id' : IDL.Principal,
    'status' : GameStatus,
    'betAmount' : IDL.Float64,
    'mode' : GameMode,
    'createdAt' : IDL.Int,
    'winner' : IDL.Opt(IDL.Principal),
    'isDemo' : IDL.Bool,
    'players' : IDL.Vec(IDL.Principal),
    'diceHistory' : IDL.Vec(DiceRoll),
    'rankedStatus' : RankedStatus,
  });
  const Player = IDL.Record({
    'principal' : IDL.Principal,
    'gamesPlayed' : IDL.Float64,
    'isPremium' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'color' : IDL.Text,
    'wins' : IDL.Float64,
    'losses' : IDL.Float64,
    'icpBalance' : IDL.Float64,
    'currentGame' : IDL.Opt(IDL.Principal),
    'draws' : IDL.Float64,
    'lastActive' : IDL.Int,
  });
  const MatchmakingRoom = IDL.Record({
    'id' : IDL.Principal,
    'status' : IDL.Variant({
      'active' : IDL.Null,
      'completed' : IDL.Null,
      'waiting' : IDL.Null,
    }),
    'creator' : IDL.Principal,
    'playerCount' : IDL.Nat,
    'isDemo' : IDL.Bool,
    'players' : IDL.Vec(IDL.Principal),
    'gameMode' : GameMode,
    'roomType' : RoomType,
    'maxPlayers' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'gamesPlayed' : IDL.Float64,
    'isPremium' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'color' : IDL.Text,
    'wins' : IDL.Float64,
    'losses' : IDL.Float64,
    'icpBalance' : IDL.Float64,
    'currentGame' : IDL.Opt(IDL.Principal),
    'draws' : IDL.Float64,
    'lastActive' : IDL.Int,
  });
  const OfficialWallet = IDL.Record({
    'balance' : IDL.Float64,
    'address' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'activatePremiumBot' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'automaticUserInitialization' : IDL.Func(
        [],
        [
          IDL.Record({
            'loginSuccess' : IDL.Bool,
            'message' : IDL.Text,
            'wallet' : Wallet,
            'playerExists' : IDL.Bool,
          }),
        ],
        [],
      ),
    'createGame' : IDL.Func(
        [GameMode, RankedStatus, IDL.Float64, IDL.Bool],
        [IDL.Principal],
        [],
      ),
    'createMatchmakingRoom' : IDL.Func(
        [RoomType, GameMode, IDL.Nat, IDL.Bool],
        [IDL.Principal],
        [],
      ),
    'createUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deposit' : IDL.Func([IDL.Float64], [IDL.Bool], []),
    'getAllBots' : IDL.Func([], [IDL.Vec(BotConfig)], ['query']),
    'getAllGames' : IDL.Func([], [IDL.Vec(GameSession)], ['query']),
    'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getAllWallets' : IDL.Func([], [IDL.Vec(Wallet)], ['query']),
    'getAvailableBots' : IDL.Func([], [IDL.Vec(BotConfig)], ['query']),
    'getAvailableGames' : IDL.Func([], [IDL.Vec(GameSession)], ['query']),
    'getAvailableRooms' : IDL.Func([], [IDL.Vec(MatchmakingRoom)], ['query']),
    'getBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDiceHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Vec(DiceRoll))],
        ['query'],
      ),
    'getGame' : IDL.Func([IDL.Principal], [IDL.Opt(GameSession)], ['query']),
    'getOfficialAccount' : IDL.Func([IDL.Bool], [IDL.Text], ['query']),
    'getOfficialWallets' : IDL.Func([], [IDL.Vec(OfficialWallet)], ['query']),
    'getPlayer' : IDL.Func([IDL.Principal], [IDL.Opt(Player)], ['query']),
    'getSystemStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalPlayers' : IDL.Int,
            'totalWallets' : IDL.Int,
            'totalGames' : IDL.Int,
            'totalBalance' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWallet' : IDL.Func([], [IDL.Opt(Wallet)], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFirstTime' : IDL.Func([], [IDL.Bool], ['query']),
    'isPremium' : IDL.Func([], [IDL.Bool], ['query']),
    'joinGame' : IDL.Func([IDL.Principal, IDL.Bool], [IDL.Bool], []),
    'joinRoom' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'leaveRoom' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'registerBot' : IDL.Func([BotDifficulty], [IDL.Principal], []),
    'rollDice' : IDL.Func(
        [IDL.Principal, IDL.Principal],
        [
          IDL.Record({
            'result' : IDL.Nat,
            'valid' : IDL.Bool,
            'seed' : IDL.Text,
          }),
        ],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePlayer' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'upgradeToPremium' : IDL.Func([], [IDL.Bool], []),
    'withdraw' : IDL.Func([IDL.Float64], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };