/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    principal: Principal;
    gamesPlayed: number;
    isPremium: boolean;
    name: string;
    createdAt: bigint;
    color: string;
    wins: number;
    losses: number;
    icpBalance: number;
    currentGame?: Principal;
    draws: number;
    lastActive: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface BotConfig {
    principal: Principal;
    balance: number;
    isPremium: boolean;
    difficulty: BotDifficulty;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Wallet {
    id: Principal;
    balance: number;
    createdAt: bigint;
    lastActive: bigint;
}
export interface GameSession {
    id: Principal;
    status: GameStatus;
    betAmount: number;
    mode: GameMode;
    createdAt: bigint;
    winner?: Principal;
    isDemo: boolean;
    players: Array<Principal>;
    rankedStatus: RankedStatus;
}
export interface OfficialWallet {
    balance: number;
    address: string;
}
export interface UserProfile {
    gamesPlayed: number;
    isPremium: boolean;
    name: string;
    createdAt: bigint;
    color: string;
    wins: number;
    losses: number;
    icpBalance: number;
    currentGame?: Principal;
    draws: number;
    lastActive: bigint;
}
export enum BotDifficulty {
    easy = "easy",
    hard = "hard",
    medium = "medium"
}
export enum GameMode {
    timed = "timed",
    challenge = "challenge",
    advanced = "advanced",
    experimental = "experimental",
    custom = "custom",
    demo = "demo",
    team = "team",
    superLudo = "superLudo",
    quick = "quick",
    tournament = "tournament",
    classic = "classic",
    twoVsTwo = "twoVsTwo",
    practice = "practice",
    bonus = "bonus",
    master = "master",
    copyClassic = "copyClassic",
    copyFast = "copyFast"
}
export enum GameStatus {
    active = "active",
    completed = "completed",
    waiting = "waiting"
}
export enum RankedStatus {
    ranked = "ranked",
    unranked = "unranked"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    activatePremiumBot(botId: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    automaticUserInitialization(): Promise<{
        loginSuccess: boolean;
        message: string;
        wallet: Wallet;
        playerExists: boolean;
    }>;
    createGame(mode: GameMode, rankedStatus: RankedStatus, betAmount: number, isDemo: boolean): Promise<Principal>;
    createUser(name: string, color: string): Promise<void>;
    deposit(amount: number): Promise<boolean>;
    getAllBots(): Promise<Array<BotConfig>>;
    getAllGames(): Promise<Array<GameSession>>;
    getAllPlayers(): Promise<Array<Player>>;
    getAllWallets(): Promise<Array<Wallet>>;
    getAvailableBots(): Promise<Array<BotConfig>>;
    getAvailableGames(): Promise<Array<GameSession>>;
    getBalance(): Promise<number>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGame(gameId: Principal): Promise<GameSession | null>;
    getOfficialAccount(isFirst: boolean): Promise<string>;
    getOfficialWallets(): Promise<Array<OfficialWallet>>;
    getPlayer(principal: Principal): Promise<Player | null>;
    getSystemStats(): Promise<{
        totalPlayers: bigint;
        totalWallets: bigint;
        totalGames: bigint;
        totalBalance: number;
    }>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWallet(): Promise<Wallet | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isFirstTime(): Promise<boolean>;
    isPremium(): Promise<boolean>;
    joinGame(gameId: Principal, isDemo: boolean): Promise<boolean>;
    registerBot(difficulty: BotDifficulty): Promise<Principal>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updatePlayer(name: string, color: string): Promise<void>;
    upgradeToPremium(): Promise<boolean>;
    withdraw(amount: number): Promise<boolean>;
}
import type { BotConfig as _BotConfig, BotDifficulty as _BotDifficulty, GameMode as _GameMode, GameSession as _GameSession, GameStatus as _GameStatus, Player as _Player, RankedStatus as _RankedStatus, UserProfile as _UserProfile, UserRole as _UserRole, Wallet as _Wallet, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async activatePremiumBot(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activatePremiumBot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activatePremiumBot(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async automaticUserInitialization(): Promise<{
        loginSuccess: boolean;
        message: string;
        wallet: Wallet;
        playerExists: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.automaticUserInitialization();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.automaticUserInitialization();
            return result;
        }
    }
    async createGame(arg0: GameMode, arg1: RankedStatus, arg2: number, arg3: boolean): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.createGame(to_candid_GameMode_n10(this._uploadFile, this._downloadFile, arg0), to_candid_RankedStatus_n12(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGame(to_candid_GameMode_n10(this._uploadFile, this._downloadFile, arg0), to_candid_RankedStatus_n12(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async createUser(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1);
            return result;
        }
    }
    async deposit(arg0: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deposit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deposit(arg0);
            return result;
        }
    }
    async getAllBots(): Promise<Array<BotConfig>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBots();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBots();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllGames(): Promise<Array<GameSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGames();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGames();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPlayers(): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlayers();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlayers();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWallets(): Promise<Array<Wallet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWallets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWallets();
            return result;
        }
    }
    async getAvailableBots(): Promise<Array<BotConfig>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableBots();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableBots();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableGames(): Promise<Array<GameSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableGames();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableGames();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBalance(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBalance();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGame(arg0: Principal): Promise<GameSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGame(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGame(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOfficialAccount(arg0: boolean): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getOfficialAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOfficialAccount(arg0);
            return result;
        }
    }
    async getOfficialWallets(): Promise<Array<OfficialWallet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOfficialWallets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOfficialWallets();
            return result;
        }
    }
    async getPlayer(arg0: Principal): Promise<Player | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayer(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayer(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSystemStats(): Promise<{
        totalPlayers: bigint;
        totalWallets: bigint;
        totalGames: bigint;
        totalBalance: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemStats();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWallet(): Promise<Wallet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWallet();
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWallet();
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isFirstTime(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFirstTime();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFirstTime();
            return result;
        }
    }
    async isPremium(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isPremium();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isPremium();
            return result;
        }
    }
    async joinGame(arg0: Principal, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.joinGame(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinGame(arg0, arg1);
            return result;
        }
    }
    async registerBot(arg0: BotDifficulty): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.registerBot(to_candid_BotDifficulty_n40(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerBot(to_candid_BotDifficulty_n40(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n42(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n42(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updatePlayer(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayer(arg0, arg1);
            return result;
        }
    }
    async upgradeToPremium(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.upgradeToPremium();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upgradeToPremium();
            return result;
        }
    }
    async withdraw(arg0: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.withdraw(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.withdraw(arg0);
            return result;
        }
    }
}
function from_candid_BotConfig_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BotConfig): BotConfig {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_BotDifficulty_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BotDifficulty): BotDifficulty {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_GameMode_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameMode): GameMode {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_GameSession_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameSession): GameSession {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_GameStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameStatus): GameStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Player_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Player): Player {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_RankedStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RankedStatus): RankedStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GameSession]): GameSession | null {
    return value.length === 0 ? null : from_candid_GameSession_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Player]): Player | null {
    return value.length === 0 ? null : from_candid_Player_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Wallet]): Wallet | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    balance: number;
    isPremium: boolean;
    difficulty: _BotDifficulty;
}): {
    principal: Principal;
    balance: number;
    isPremium: boolean;
    difficulty: BotDifficulty;
} {
    return {
        principal: value.principal,
        balance: value.balance,
        isPremium: value.isPremium,
        difficulty: from_candid_BotDifficulty_n17(_uploadFile, _downloadFile, value.difficulty)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    status: _GameStatus;
    betAmount: number;
    mode: _GameMode;
    createdAt: bigint;
    winner: [] | [Principal];
    isDemo: boolean;
    players: Array<Principal>;
    rankedStatus: _RankedStatus;
}): {
    id: Principal;
    status: GameStatus;
    betAmount: number;
    mode: GameMode;
    createdAt: bigint;
    winner?: Principal;
    isDemo: boolean;
    players: Array<Principal>;
    rankedStatus: RankedStatus;
} {
    return {
        id: value.id,
        status: from_candid_GameStatus_n22(_uploadFile, _downloadFile, value.status),
        betAmount: value.betAmount,
        mode: from_candid_GameMode_n24(_uploadFile, _downloadFile, value.mode),
        createdAt: value.createdAt,
        winner: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.winner)),
        isDemo: value.isDemo,
        players: value.players,
        rankedStatus: from_candid_RankedStatus_n27(_uploadFile, _downloadFile, value.rankedStatus)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    gamesPlayed: number;
    isPremium: boolean;
    name: string;
    createdAt: bigint;
    color: string;
    wins: number;
    losses: number;
    icpBalance: number;
    currentGame: [] | [Principal];
    draws: number;
    lastActive: bigint;
}): {
    principal: Principal;
    gamesPlayed: number;
    isPremium: boolean;
    name: string;
    createdAt: bigint;
    color: string;
    wins: number;
    losses: number;
    icpBalance: number;
    currentGame?: Principal;
    draws: number;
    lastActive: bigint;
} {
    return {
        principal: value.principal,
        gamesPlayed: value.gamesPlayed,
        isPremium: value.isPremium,
        name: value.name,
        createdAt: value.createdAt,
        color: value.color,
        wins: value.wins,
        losses: value.losses,
        icpBalance: value.icpBalance,
        currentGame: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.currentGame)),
        draws: value.draws,
        lastActive: value.lastActive
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gamesPlayed: number;
    isPremium: boolean;
    name: string;
    createdAt: bigint;
    color: string;
    wins: number;
    losses: number;
    icpBalance: number;
    currentGame: [] | [Principal];
    draws: number;
    lastActive: bigint;
}): {
    gamesPlayed: number;
    isPremium: boolean;
    name: string;
    createdAt: bigint;
    color: string;
    wins: number;
    losses: number;
    icpBalance: number;
    currentGame?: Principal;
    draws: number;
    lastActive: bigint;
} {
    return {
        gamesPlayed: value.gamesPlayed,
        isPremium: value.isPremium,
        name: value.name,
        createdAt: value.createdAt,
        color: value.color,
        wins: value.wins,
        losses: value.losses,
        icpBalance: value.icpBalance,
        currentGame: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.currentGame)),
        draws: value.draws,
        lastActive: value.lastActive
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
}): BotDifficulty {
    return "easy" in value ? BotDifficulty.easy : "hard" in value ? BotDifficulty.hard : "medium" in value ? BotDifficulty.medium : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    completed: null;
} | {
    waiting: null;
}): GameStatus {
    return "active" in value ? GameStatus.active : "completed" in value ? GameStatus.completed : "waiting" in value ? GameStatus.waiting : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timed: null;
} | {
    challenge: null;
} | {
    advanced: null;
} | {
    experimental: null;
} | {
    custom: null;
} | {
    demo: null;
} | {
    team: null;
} | {
    superLudo: null;
} | {
    quick: null;
} | {
    tournament: null;
} | {
    classic: null;
} | {
    twoVsTwo: null;
} | {
    practice: null;
} | {
    bonus: null;
} | {
    master: null;
} | {
    copyClassic: null;
} | {
    copyFast: null;
}): GameMode {
    return "timed" in value ? GameMode.timed : "challenge" in value ? GameMode.challenge : "advanced" in value ? GameMode.advanced : "experimental" in value ? GameMode.experimental : "custom" in value ? GameMode.custom : "demo" in value ? GameMode.demo : "team" in value ? GameMode.team : "superLudo" in value ? GameMode.superLudo : "quick" in value ? GameMode.quick : "tournament" in value ? GameMode.tournament : "classic" in value ? GameMode.classic : "twoVsTwo" in value ? GameMode.twoVsTwo : "practice" in value ? GameMode.practice : "bonus" in value ? GameMode.bonus : "master" in value ? GameMode.master : "copyClassic" in value ? GameMode.copyClassic : "copyFast" in value ? GameMode.copyFast : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ranked: null;
} | {
    unranked: null;
}): RankedStatus {
    return "ranked" in value ? RankedStatus.ranked : "unranked" in value ? RankedStatus.unranked : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BotConfig>): Array<BotConfig> {
    return value.map((x)=>from_candid_BotConfig_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GameSession>): Array<GameSession> {
    return value.map((x)=>from_candid_GameSession_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Player>): Array<Player> {
    return value.map((x)=>from_candid_Player_n30(_uploadFile, _downloadFile, x));
}
function to_candid_BotDifficulty_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BotDifficulty): _BotDifficulty {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_GameMode_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameMode): _GameMode {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_RankedStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RankedStatus): _RankedStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gamesPlayed: number;
    isPremium: boolean;
    name: string;
    createdAt: bigint;
    color: string;
    wins: number;
    losses: number;
    icpBalance: number;
    currentGame?: Principal;
    draws: number;
    lastActive: bigint;
}): {
    gamesPlayed: number;
    isPremium: boolean;
    name: string;
    createdAt: bigint;
    color: string;
    wins: number;
    losses: number;
    icpBalance: number;
    currentGame: [] | [Principal];
    draws: number;
    lastActive: bigint;
} {
    return {
        gamesPlayed: value.gamesPlayed,
        isPremium: value.isPremium,
        name: value.name,
        createdAt: value.createdAt,
        color: value.color,
        wins: value.wins,
        losses: value.losses,
        icpBalance: value.icpBalance,
        currentGame: value.currentGame ? candid_some(value.currentGame) : candid_none(),
        draws: value.draws,
        lastActive: value.lastActive
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameMode): {
    timed: null;
} | {
    challenge: null;
} | {
    advanced: null;
} | {
    experimental: null;
} | {
    custom: null;
} | {
    demo: null;
} | {
    team: null;
} | {
    superLudo: null;
} | {
    quick: null;
} | {
    tournament: null;
} | {
    classic: null;
} | {
    twoVsTwo: null;
} | {
    practice: null;
} | {
    bonus: null;
} | {
    master: null;
} | {
    copyClassic: null;
} | {
    copyFast: null;
} {
    return value == GameMode.timed ? {
        timed: null
    } : value == GameMode.challenge ? {
        challenge: null
    } : value == GameMode.advanced ? {
        advanced: null
    } : value == GameMode.experimental ? {
        experimental: null
    } : value == GameMode.custom ? {
        custom: null
    } : value == GameMode.demo ? {
        demo: null
    } : value == GameMode.team ? {
        team: null
    } : value == GameMode.superLudo ? {
        superLudo: null
    } : value == GameMode.quick ? {
        quick: null
    } : value == GameMode.tournament ? {
        tournament: null
    } : value == GameMode.classic ? {
        classic: null
    } : value == GameMode.twoVsTwo ? {
        twoVsTwo: null
    } : value == GameMode.practice ? {
        practice: null
    } : value == GameMode.bonus ? {
        bonus: null
    } : value == GameMode.master ? {
        master: null
    } : value == GameMode.copyClassic ? {
        copyClassic: null
    } : value == GameMode.copyFast ? {
        copyFast: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RankedStatus): {
    ranked: null;
} | {
    unranked: null;
} {
    return value == RankedStatus.ranked ? {
        ranked: null
    } : value == RankedStatus.unranked ? {
        unranked: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BotDifficulty): {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
} {
    return value == BotDifficulty.easy ? {
        easy: null
    } : value == BotDifficulty.hard ? {
        hard: null
    } : value == BotDifficulty.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
